BOARD_ROWS = 20
BOARD_COLUMNS = 10

SQUARE_SIZE = 32

DROP_HEIGHT  = 3 * SQUARE_SIZE

BOARD_RIGHT_BUFFER = 4 * SQUARE_SIZE
BOARD_LEFT_BUFFER = 4 * SQUARE_SIZE
BOARD_TOP_BUFFER = 4 * SQUARE_SIZE
BOARD_BOTTOM_BUFFER = 4 * SQUARE_SIZE

BOARD_WIDTH = SQUARE_SIZE * BOARD_COLUMNS
BOARD_HEIGHT = SQUARE_SIZE * BOARD_ROWS

SCR_WIDTH = BOARD_WIDTH + BOARD_RIGHT_BUFFER + BOARD_LEFT_BUFFER
SCR_HEIGHT = BOARD_HEIGHT + BOARD_TOP_BUFFER + BOARD_BOTTOM_BUFFER

# Board Coordinate Definitions
TOP_LEFT_BOARD_CORNER = (BOARD_LEFT_BUFFER, BOARD_TOP_BUFFER)
TOP_RIGHT_BOARD_CORNER = (BOARD_LEFT_BUFFER + BOARD_WIDTH, BOARD_TOP_BUFFER)
BOTTOM_LEFT_BOARD_CORNER = (BOARD_LEFT_BUFFER, BOARD_TOP_BUFFER + BOARD_HEIGHT)
BOTTOM_RIGHT_BOARD_CORNER = (BOARD_LEFT_BUFFER + BOARD_WIDTH, BOARD_TOP_BUFFER + BOARD_HEIGHT)