BOARD_ROWS = 20
BOARD_COLUMNS = 10

GRID_SIZE = 32
GRID_ALPHA = 50
GRID_OUTLINE_WIDTH = 3

DROP_HEIGHT = 3 * GRID_SIZE

BOARD_RIGHT_BUFFER = 6 * GRID_SIZE
BOARD_LEFT_BUFFER = 6 * GRID_SIZE
BOARD_TOP_BUFFER = 4 * GRID_SIZE
BOARD_BOTTOM_BUFFER = 4 * GRID_SIZE

BOARD_WIDTH = GRID_SIZE * BOARD_COLUMNS
BOARD_HEIGHT = GRID_SIZE * BOARD_ROWS

SCR_WIDTH = BOARD_WIDTH + BOARD_RIGHT_BUFFER + BOARD_LEFT_BUFFER
SCR_HEIGHT = BOARD_HEIGHT + BOARD_TOP_BUFFER + BOARD_BOTTOM_BUFFER

# Board Coordinate Definitions
TOP_LEFT_BOARD_CORNER = (BOARD_LEFT_BUFFER, BOARD_TOP_BUFFER)
TOP_RIGHT_BOARD_CORNER = (BOARD_LEFT_BUFFER + BOARD_WIDTH, BOARD_TOP_BUFFER)
BOTTOM_LEFT_BOARD_CORNER = (BOARD_LEFT_BUFFER, BOARD_TOP_BUFFER + BOARD_HEIGHT)
BOTTOM_RIGHT_BOARD_CORNER = (BOARD_LEFT_BUFFER + BOARD_WIDTH, BOARD_TOP_BUFFER + BOARD_HEIGHT)

def toGridSize(x: int) -> int:
    """Converts pixel size to grid size e.g. 160 pixels to 5 squares, where grid size = 32.

    Args:
        x (int): Any length of pixels

    Returns:
        int: That length divided by the grid size
    """    
    return x / GRID_SIZE