import game.game_settings as gs

BOARD_ROWS = 20
BOARD_COLUMNS = 10

GRID_SIZE = gs.GAME_SIZE * 2
INNER_GRID_ALPHA = 40
OUTER_GRID_ALPHA = 200
BACKGROUND_ALPHA = 150
GRID_OUTLINE_WIDTH = 3

MAX_PIECE_LENGTH = 4
DROP_HEIGHT = 2
FLOOR_SIZE = 4

BOARD_HEIGHT_BUFFER = DROP_HEIGHT + MAX_PIECE_LENGTH

HELD_PIECE_X_POS = MAX_PIECE_LENGTH - 8
HELD_PIECE_Y_POS = 4 + FLOOR_SIZE

QUEUED_PIECES_X_POS = MAX_PIECE_LENGTH + 9
QUEUED_PIECES_Y_POS = 4 + FLOOR_SIZE
QUEUED_PIECES_VERTICAL_SPACING = 3

BOARD_HEIGHT = BOARD_ROWS + BOARD_HEIGHT_BUFFER
BOARD_WIDTH = BOARD_COLUMNS

BOARD_RIGHT_BUFFER = 7 * GRID_SIZE
BOARD_LEFT_BUFFER = 7 * GRID_SIZE
BOARD_TOP_BUFFER = 4 * GRID_SIZE
BOARD_BOTTOM_BUFFER = 4 * GRID_SIZE

BOARD_PIXEL_WIDTH = GRID_SIZE * BOARD_COLUMNS
BOARD_PIXEL_HEIGHT = GRID_SIZE * BOARD_ROWS

SCR_WIDTH = BOARD_PIXEL_WIDTH + BOARD_RIGHT_BUFFER + BOARD_LEFT_BUFFER
SCR_HEIGHT = BOARD_PIXEL_HEIGHT + BOARD_TOP_BUFFER + BOARD_BOTTOM_BUFFER

# Board Coordinate Definitions
TOP_LEFT_BOARD_CORNER = (BOARD_LEFT_BUFFER - 2, BOARD_TOP_BUFFER)
TOP_RIGHT_BOARD_CORNER = (BOARD_LEFT_BUFFER + BOARD_PIXEL_WIDTH + 1, BOARD_TOP_BUFFER)
BOTTOM_LEFT_BOARD_CORNER = (BOARD_LEFT_BUFFER - 2, BOARD_TOP_BUFFER + BOARD_PIXEL_HEIGHT + 1)
BOTTOM_RIGHT_BOARD_CORNER = (BOARD_LEFT_BUFFER + BOARD_PIXEL_WIDTH + 1, BOARD_TOP_BUFFER + BOARD_PIXEL_HEIGHT + 1)