# Base board size
BOARD_ROWS = 20
BOARD_COLUMNS = 10

# Piece values
PIECE_COMPONENTS = 4

# Score Values
TETRIS_LINE_CLEARS = 4

INNER_GRID_ALPHA = 40
OUTER_GRID_ALPHA = 200
BACKGROUND_ALPHA = 150
GRID_OUTLINE_WIDTH = 3

# Vertical adjustment values
MAX_PIECE_LENGTH = 4
DROP_HEIGHT = 2
BOARD_HEIGHT_BUFFER = DROP_HEIGHT + MAX_PIECE_LENGTH

# Adjusted board size
BOARD_HEIGHT = BOARD_ROWS + BOARD_HEIGHT_BUFFER
BOARD_WIDTH = BOARD_COLUMNS
BOARD_HEIGHT_RANGE_INCR = range(BOARD_HEIGHT_BUFFER, BOARD_HEIGHT) # Incrementing height range

# Held piece position
HELD_PIECE_X_POS = MAX_PIECE_LENGTH - 8
HELD_PIECE_Y_POS = 4 + MAX_PIECE_LENGTH

# Queued piece position
QUEUED_PIECES_X_POS = MAX_PIECE_LENGTH + 9
QUEUED_PIECES_Y_POS = 4 + MAX_PIECE_LENGTH
QUEUED_PIECES_VERTICAL_SPACING = 3